### ISSUE TITLE
Improve first run experience: icon font generation stuck in loop

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#100]
- [ ] Remove icon font task
- [ ] Add SVG icons

On first run in a clean repo, the `gulp` task gets stuck in a loop with the icon font.

![](http://c.xvr.io/0I0T3Q0h0u2u/Image%202016-04-29%20at%2010.30.38%20AM.png)

On second run, the issue is gone.

**Comment by xavez** [comment]
Additional info: this always occurs when editing an `scss` file

**Comment by Wolfr** [comment]
Is this blocking your current work?

**Comment by xavez** [comment]
It was but @thomastuts fixed it already, just need to port the changes here I think ;-)

**Comment by Wolfr** [comment]
@thomastuts @xavez this issue still occurs when changing any CSS, was it fixed and if so where?

**Comment by Wolfr** [comment]
So, I had the same problem as @xavez . I ported some code from the project where it was fixed (presenter) and thus removed the icon font altogether from Bedrock.

I think we can all agree it causes too much problems and has caused us too much problems in the past for various reasons. Going forward the preferred implementation is SVG.
