### ISSUE TITLE
"Dark" skin for dark UI projects

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#125]
When you set "dark" to true in the bedrock config, the following changes:

* A different codemirror theme is loaded (dark theme)
* The prototype navigation changes color

The styling of all of this needs to be scoped to bedrock only, this is tricky.

**Comment by Wolfr** [comment]
You know which dark themed project I am talking about... this was "hacked" into that codebase making the core non-upgradeable without some manual work. I think it would be good to have this so we can upgrade said project to the latest Bedrock version.

**Comment by Wolfr** [comment]
See #135 .

**Comment by Wolfr** [comment]
This was released in 1.1.

@thomastuts do you see a possibility to make the switch to dark mode happen in 1 place instead of 2 places? Now you have to adjust a config variable and a CSS variable.

**Comment by thomastuts** [comment]
This used to be the case, and Bedrock would add the appropriate UI class to the DOM so we could scope styles to this class. However, I see that you've opted to use `$br-dark` in SCSS instead of using scoped classes, resulting in going from 1 variable to 2. What's the reasoning for using a variable in SCSS too if we can just scope it to a body/HTML class?

**Comment by Wolfr** [comment]
Then you can use `@if $br-dark == true { }` in your CSS and you don't generate any cruft you don't need.

This also avoids overrides in CSS which is something that we want to avoid.

If somehow we could expose the bedrock config as CSS variables... that would be awesome.

**Comment by Wolfr** [comment]
I guess for now it's better to revert the behavior but keep the styling updates. Issue created #166

**Comment by Wolfr** [comment]
This was released in 1.1.

https://github.com/mono-company/bedrock/releases/tag/1.1final
