### ISSUE TITLE
icon-fonts scss file cannot be found on first run

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#127]
With a clean install, on first run, Bedrock cannot find the `icon-font` file

![](http://c.xvr.io/3E1q3i2M2C11/Image%202016-12-03%20at%203.19.53%20PM.png)

This probably needs a fix in the gulp tasks somewhere.

**Comment by Wolfr** [comment]
I made it the default that you don't use icon fonts.

Since this is a generated file that is also gitignored it is pretty hard to provide a good first run experience here.

At least now most Bedrock users won't see the error until they decide to use icon fonts.
