### ISSUE TITLE
Make icon mixin available in content area?

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#128]
At the moment a lot of the docs look like this:

    include ../../../../core/templates/mixins/icon

    .c-toolbar.c-toolbar--size-small
        .c-toolbar__left
            .c-toolbar__item
                h3.c-toolbar-title Toolbar title
            .c-toolbar__item
                p.c-toolbar-text Just some helpful text
            .c-toolbar__item
        .c-toolbar__right
            .c-toolbar__item
                .c-button-toolbar
                    button.c-button.c-button--default.c-button--small
                        .c-button__label A button
                    button.c-button.c-button--icon.c-button--default.c-button--small
                        +icon('close')

You have to remember to include the icon mixin.

It would make it more convenient if we could make this available globally so not every pattern has to have this declaration.

**Comment by Wolfr** [comment]
@thomastuts This one is something I encounter a lot. Any thoughts?

**Comment by thomastuts** [comment]
AFAIK you can't make mixins global in Jade, so there's not really a way around this. You could create a layout that imports the icon, but then you'd have to extend that layout — resulting in the same issue of having to make sure you don't forget to do so.

**Comment by Wolfr** [comment]
Since the styleguide page contains blocks that are really just HTML renders of the above code, is there no way to put something "in between" that renders that block of code with the knowledge of the +icon mixin? 

something like: default-styleguide-render-template.jade
   include ../../../../core/templates/mixins/icon
   block component

component.jade --> code for component itself that automatically extends default-styleguide-render-template.jade

Just freewheeling here. Maybe you get some ideas :)
