### ISSUE TITLE
Icon mixin is not exposed in docs

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#140]
If you use the icon mixin within the documentation.

You can find a reduced test case in this branch:
https://github.com/mono-company/bedrock/tree/bugfixes/iconsindocs

Upon the initial `gulp` action Bedrock immediately renders an error

https://cl.ly/3k0f0L0b083c

**Comment by Wolfr** [comment]
@thomastuts This one is blocking me from some current work, this is the issue with the highest priority of all for me.

**Comment by thomastuts** [comment]
Fixed in https://github.com/mono-company/bedrock/commit/6ffd4d6cf79146889285a3f54cdfeda1b053a845

**Comment by Wolfr** [comment]
❤️
