### ISSUE TITLE
Collapse bug in tree when templates have the same name

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#147]
If you have a lot of items a bug occurs in the tree.

I can't show this in a screenshot because it occurs in a client project.

@thomastuts I will add you to said project and send you a private screencast.

**Comment by Wolfr** [comment]
The same occured in another project, so we should look into this when some work on Bedrock starts again.

**Comment by Wolfr** [comment]
We encountered this bug again. It occurs when templates have the same name.

We can work around it but it would be better if it was possible for templates to have similar names. I think the way the tree key gets saved needs to be adjusted.

**Comment by xavez** [comment]
I tried fixing this, check out pull request #154
