### ISSUE TITLE
Improve build times

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#150]
<img width="615" alt="screen shot 2017-05-11 at 11 28 46" src="https://cloud.githubusercontent.com/assets/12690/25942401/0bb7df6a-363d-11e7-88f1-a2d8b8fd2e49.png">

**Comment by Wolfr** [comment]
@thomastuts would this be easy? To switch to yarn?

**Comment by Wolfr** [comment]
(We are using circleCI to build bedrock builds which always starts from the beginning e.g. `npm install`)

**Comment by Wolfr** [comment]
When you do a local build it takes 20 secs

<img width="762" alt="screen shot 2017-05-16 at 12 56 42" src="https://cloud.githubusercontent.com/assets/12690/26102845/2dae3c92-3a37-11e7-8ea5-7a6bbe237775.png">

But a server build takes 3 mins, because it starts from scratch

<img width="1248" alt="screen shot 2017-05-16 at 12 56 54" src="https://cloud.githubusercontent.com/assets/12690/26102851/316bb2e2-3a37-11e7-8ef5-dfd62c2d4e4f.png">

How can we improve this?

**Comment by xavez** [comment]
I think we can check out CircleCI 2.0, which supposedly has better caching and faster build times.

**Comment by Wolfr** [comment]
This is in progress on another repo.
