### ISSUE TITLE
Improve icon documentation

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#152]
* When there are subfolders in /icons/, render these out as separate icon documentation.
* Allow icon mixin to reference a path.

This will allow you to mirror Sketch symbol logic in HTML.

For example, we have 4 icons of the type "control", and 4 icons that are regular icons. The folder structure is as follows:

* other-icon-1
* other-icon-2
* other-icon-3
* other-icon-4
* ctrl/icon-1
* ctrl/icon-2
* ctrl/icon-3
* ctrl/icon-4

This should render 2 separate documentation samples in the icons styleguide.

When you want to access these icons, you would write:

    +icon('other-icon-1')
    +icon('ctrl/other-icon-1')

**Comment by simonwuyts** [comment]
Makes sense! Not always necessary, but in some cases it might be very handy.

**Comment by xavez** [comment]
If you mean to render them with a separate heading but still one page, I’m all for it!

**Comment by Wolfr** [comment]
Yes they will be on the same page but in logical groups.

Like this:

<img width="630" alt="screen shot 2017-05-19 at 22 53 28" src="https://cloud.githubusercontent.com/assets/12690/26266528/0057f934-3ce6-11e7-8826-2a84b35dfff0.png">

**Comment by Wolfr** [comment]
<img width="917" alt="screen shot 2017-05-25 at 18 05 31" src="https://cloud.githubusercontent.com/assets/12690/26458843/c818c4f2-4174-11e7-8943-cddea4690143.png">

Here is a real life example where 2 icon categories would be cool

**Comment by thomastuts** [comment]
This feature was added in a separate branch (`feature/icon-categories`, https://github.com/mono-company/bedrock/commit/900f9d2a43f72d622ce96a5d30d9bfca46cc335d). The way this works is like you described above: any base icons are in the top icon list (like they are above in your screenshots). Any additional icon 'categories' (a category is a subfolder in `contents/icons`) are rendered below the base icons list in the same manner.

You can use the icon mixin like before, it now also supports categories as requested:

```pug
+icon('example')
+icon('ctrl/example')
```

Note that the category slash in the icon name is replaced with a `-` for the icon class, so the second mixin would result in an icon with the classes `.svg-icon.svg-icon-ctrl-example`.

This feature is only supported for the SVG icons at the moment, as I wasn't sure if it was worth the hassle of adding it to the icon font as well (which is a little more involved). See the Bedrock Slack channel for more info.

**Comment by Wolfr** [comment]
@thomastuts I dropped a folder called "16" with a bunch of icons on the icons folder to test this functionality and Bedrock immediately errored. It seems it was looking for `example.svg` whereas what I dropped was a folder without an `example.svg`.

I commited the error which also occurs after a `gulp` restart to https://github.com/mono-company/bedrock/commit/ac2961c2c4b153782054773ceeb5c66c6667adf0 .

**Comment by Wolfr** [comment]
This was released in 1.1.

Thank you @thomastuts 🎉
