### ISSUE TITLE
Page states

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#153]
In my older prototypes I had a way to show different states of a page in a separate way. It was very interesting to see different page states in large scale prototypes.

Proposal: if a page has -- in the filename it shows up as a state in a page state list instead of in the tree.

So we can have `overview.jade` and `overview--blank.jade` and these will show up in the bottom left of the tree.

<img width="505" alt="screen shot 2017-05-17 at 15 34 25" src="https://cloud.githubusercontent.com/assets/12690/26156352/53fd64a6-3b16-11e7-8244-3e25ab2876f2.png">

**Comment by Wolfr** [comment]
<img width="671" alt="screen shot 2017-05-17 at 15 40 48" src="https://cloud.githubusercontent.com/assets/12690/26156628/3c21ab2a-3b17-11e7-8851-4c8bcb4d4008.png">

here's a real world example

**Comment by xavez** [comment]
Yeah I’ve missed this in SweepBright. Especially since the side menu there is, well, huge :D

**Comment by Wolfr** [comment]
1. https://cl.ly/0S3c2W3T1u1U
2. https://cl.ly/3D3l2X2e1H40

**Comment by Wolfr** [comment]
Let's keep this open until it is fully tested.

**Comment by Wolfr** [comment]
This was released in 1.1.

Thank you @thomastuts 🎉
