### ISSUE TITLE
Notify 

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#159]
![input-example](https://cloud.githubusercontent.com/assets/12690/26466226/3d2526b4-418e-11e7-8f90-22a2245190b1.gif)

the source code references this https://www.npmjs.com/package/node-notifier but I've never seen this work/in use, can this code be removed? Was this an experiment?

**Comment by Wolfr** [comment]
My bad it does work for sass, but not for jade errors I think

**Comment by thomastuts** [comment]
The reasoning behind using no notifications for Jade errors is that you'll be looking at your prototype anyway, so any Jade errors are shown directly in the app itself. Come to think of it, it also does that for SASS (and JS too I believe), so we can remove this notification feature if you'd like.

**Comment by Wolfr** [comment]
It works, this was just my investigation, I will leave it alone :)
