### ISSUE TITLE
Bug: if there are no icons in the base folder, you get an error

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#162]
if -all- icons are categorized (i.e. the icons folder doesn't have a single SVG file in but only folders), you get an error.

Example:

<img width="282" alt="screen shot 2017-06-01 at 14 57 24" src="https://cloud.githubusercontent.com/assets/12690/26680695/b2fd566c-46da-11e7-9692-3511607d7451.png">
<img width="1048" alt="screen shot 2017-06-01 at 14 57 29" src="https://cloud.githubusercontent.com/assets/12690/26680696/b317a166-46da-11e7-930e-0b6fbd7178d8.png">

**Comment by Wolfr** [comment]
You can reproduce this in bedrock 1.1 by deleting example.svg

<img width="252" alt="screen shot 2017-06-01 at 15 00 00" src="https://cloud.githubusercontent.com/assets/12690/26680802/08aa8e86-46db-11e7-9fb1-a71e00cb174a.png">

**Comment by thomastuts** [comment]
Should be fixed in https://github.com/mono-company/bedrock/commit/71a2b8a2bd1d3e105724004c5b2271933613ca0a

**Comment by Wolfr** [comment]
Great!
