### ISSUE TITLE
When using an icon font, icons don’t show on the page

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#171]
I think this is due to a bug in `/core/templates/mixins/icon-overview.jade` but I’m not sure.

**Comment by xavez** [comment]
After some investigation I’m pretty sure this is the culprit

https://github.com/mono-company/bedrock/blob/130337601e6799980d1a413016fd19ded8317bcb/core/templates/mixins/icon-overview.jade#L4

It was committed by @thomastuts, maybe he can explain a bit more about the reasoning so that we can fix it without breaking other stuff

**Comment by Wolfr** [comment]
Does this occur in Bedrock (this project) or in your specific project?

**Comment by Wolfr** [comment]
The guard code is meant for the case when you don't have any icons at all (no icons folder).

I investigated it and have a fix.

**Comment by Wolfr** [comment]
If it is a new Bedrock project, make sure you are loading the CSS:

<img width="502" alt="screen shot 2017-07-13 at 22 15 44" src="https://user-images.githubusercontent.com/12690/28185759-da4b2654-6818-11e7-9fb7-a33bd2666820.png">

Make sure generateIconFont is set to true:

<img width="346" alt="screen shot 2017-07-13 at 22 16 15" src="https://user-images.githubusercontent.com/12690/28185775-eb914150-6818-11e7-91c4-8b31bb77626c.png">

Then, upgrade to the latest version, which I tested and confirmed working.

**Comment by xavez** [comment]
Solution confirmed! 👍
