### ISSUE TITLE
Badges on repo

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#179]
I wonder how we can get a badge on the repo.

https://www.npmjs.com/package/badge-list 

To look more professional 💪 

Anyone has experience with this?

@simonwuyts @thomastuts

**Comment by thomastuts** [comment]
You can use http://shields.io/ for this. Not sure if there's anything interesting in this list that we can use.

**Comment by Wolfr** [comment]
Just the last version number?

We don't have any tests.

Also considering moving the contents of BEDROCK-README.md back to README.md so it's more clear on Github itself how to get started.

**Comment by Wolfr** [comment]
I did this, we have a badge now! 

https://github.com/mono-company/bedrock
