### ISSUE TITLE
ctrl+m is a reserved key combination in Edge on Windows

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#180]
We may want to consider a different key combination to open the menu, since <kbd>ctrl+m</kbd> is a reserved key combination in Edge on Windows. It opens the sidebar with the reading list.

**Comment by Wolfr** [comment]
You can also use Ctrl + B. I encountered this problem some time ago. See prototype-nav.js

Composed tersely on a tiny keyboard

**Comment by xavez** [comment]
OK, this issue is actually solved then.
