### ISSUE TITLE
Copy [bootstrap/foundation/whatever] to its own folder

### ISSUE THREAD

**Issue by xavez** [mono-company/bedrock#47]
## What is the problem?

I cannot easily view the bootstrap source files / search for a certain line of code that is responsible for a certain output.

## Why do we want this?

Because you sometimes want to see the line of code that is responsible for a certain result, even if it comes from bootstrap or foundation core.

## What is the issue?

`.node_modules` is ignored in my editor – it is probably also ignored in many other people’s editors because a search or file switch within a project would be slower and return more irrelevant results. 

## Proposed solution

We can:

- Create a new directory `/vendor` and add a `.gitignore` file in it.
- Create a gulp task to copy the toolkit we load via `npm` from `.node_modules` to this folder.
- Adjust the paths in the scss files.

**Comment by Wolfr** [comment]
I think we were trying to fix Bootstrap upgradeability within a prototype context, it is not necessary.

**Comment by xavez** [comment]
I think there was another reason, but it seems to have been solved already in some previous version :-)

**Comment by Wolfr** [comment]
Well we fixed/sidestepped it by copying bootstrap to the SCSS folder instead of referencing it from node_modules.
