### ISSUE TITLE
Track all errors and render them in Express

### ISSUE THREAD

**Issue by thomastuts** [mono-company/bedrock#75]
It might be worth investigating if we can store any potential errors (like Sass compilation errors, errors in data, ...) on the `global` scope, and then render them in Express conditionally (and clearing the error). This would make spotting errors even easier, and would probably eliminate the need for the notifiers being used right now.

**Comment by Wolfr** [comment]
Investigate rendering errors on-screen (i.e. in the browser tab itself)

**Comment by thomastuts** [comment]
This has now been implemented in the following manner:

- On a SASS or JS error, the error is stored on the server
- On subsequent SASS or JS compiles, the error is cleared if there isn't one anymore
- The server checks to see if there are any errors present, and if so, renders the `core/templates/error.jade` template
- A manual refresh is required when the errors have been solved

This view could benefit from some styling (and copy) love, but it's functional.

**Comment by Wolfr** [comment]
Thank you. This is wonderful.
