### ISSUE TITLE
Icon font optional

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#81]
We can't assume everyone needs the icon font generation and thus it needs to be optional (`fontcustom` it is the most fragile dependency)

**Comment by kjvdven** [comment]
I pulled the project and tried to set it up (npm install) and all I got was an fontcustom error (when I ran gulp).

    Error: Command failed: /bin/sh -c fontcustom compile /Users/kris/Code/_resources/bedrock/content/icon-font-source --output ./___tmp___ --css-selector .glyphicon-{{glyph}} --font_name icon-font --force true --no_hash true
    /bin/sh: fontcustom: command not found

I think I'm missing something there.

**Comment by Wolfr** [comment]
What OS are you on?

Did you install fontforge?

**Comment by kjvdven** [comment]
I forget to install the gem fontcustom, better read the manual.

**Comment by Wolfr** [comment]
The icon font is optional through the `icons.generateIconsFromSource` option in `config.js`.

**Comment by Wolfr** [comment]
When I remove this part from the Bedrock config

  icons: {
    generateIconFont: false,
    hasSvgIcons: true
  },

I get an error

<img width="758" alt="screen shot 2017-09-21 at 09 34 26" src="https://user-images.githubusercontent.com/12690/30684067-13e51406-9eb0-11e7-82ca-ca7264d07970.png">

Can we make it so that the icon font and the svg icons are both optional?

**Comment by Wolfr** [comment]
Too niche to work on
