### ISSUE TITLE
___tmp___ folder is not created

### ISSUE THREAD

**Issue by dimitrydhondt** [mono-company/bedrock#82]
When I run the bedrockinvoicedemo the server crashes with a message stating that it can not list the ./___tmp___ folder. Perhaps the temp folder for gulp should be created if not present ? When I create manually it works once, but the process seems to remove the folder automatically.

P.S.: You may want to add to the docs that npm install -g gulp is required to run the demo/bedrock. And you may want to document where the configuration lives, and how to change the default port. On Cloud9 I must run it on 8080 to be available online.

![screenshot 2016-01-06 at 11 54 44](https://cloud.githubusercontent.com/assets/6338317/12140999/4f019b5c-b46c-11e5-93fc-bd9f7e817f12.png)

**Comment by Wolfr** [comment]
I updated the README with more documentation about the config file.

https://github.com/mono-company/bedrock/commit/e6a89d8c2d79be604529f650af90fc8034b9c3e0

@thomastuts Is changing the port also a config option that can be set?

**Comment by thomastuts** [comment]
> @thomastuts Is changing the port also a config option that can be set?

Not yet, we can add this in one of the upcoming versions. Only having one port is kind of a problem though, since we actually run two servers: Express for the Jade compilation and serving of static files, and BrowserSync that proxies to the Express server to add the livereload functionality.

**Comment by kjvdven** [comment]
I did get the same problem, but after following the install instructions on [fontcustom](https://github.com/FontCustom/fontcustom) the error didn't show up anymore. 

    # On Mac
    brew install fontforge --with-python
    brew install eot-utils
    gem install fontcustom
