### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#83]
How do you change the order of the documentation?

Maybe we should order it by the title? Then you can use numbering to sort the files.

<img width="694" alt="screen shot 2016-01-18 at 16 35 42" src="https://cloud.githubusercontent.com/assets/12690/12395389/9454eb0c-be01-11e5-9ad3-8ae1a236e88d.png">

**Comment by thomastuts** [comment]
This can now be achieved by adding an 'order' attribute in the doc front-matter. Docs **without** an order attribute will appear below the ones that do have one.

**Comment by Wolfr** [comment]
Great! :+1:
