### ISSUE TITLE
/modules folder optional for templates

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#85]
We shouldn't force people to use a `/modules` folder.

**Comment by Wolfr** [comment]
Related #79 . If this is implemented #79 is obsolete.

**Comment by Wolfr** [comment]
I got this error again, you should be able to use Bedrock without needing a `/modules/` folder.

**Comment by Wolfr** [comment]
I got this error again, just noting. When we get to work on Bedrock we should prioritize this imo, this occurs pretty often in new projects.

**Comment by thomastuts** [comment]
This is now supported — the `modules/` folder is completely optional. Users are free to use whatever directory structure they like, and the page tree will render accordingly. One thing to note is that we now had to introduce a concept of 'private' directories (e.g. the ones for patterns and layouts). Any directory starting with a `_` will not be indexed and shown in the page tree.
